import BUILDING_TYPES from './buildingTypes';
import { GOLD, ELIXIR, BLACK } from './resources';
import { SECONDS, MINUTES, HOURS, DAYS } from './times';
import { K, M } from './quantities';

export default {
  [BUILDING_TYPES.BUILDER_HUT]: [
    {level: 1, requiredTH: 0, picture: require('../assets/images/Builder_Hut.png')},
    {level: 2, requiredTH: 0, picture: require('../assets/images/Builder_Hut.png')},
    {level: 3, requiredTH: 0, picture: require('../assets/images/Builder_Hut.png')},
    {level: 4, requiredTH: 0, picture: require('../assets/images/Builder_Hut.png')},
    {level: 5, requiredTH: 0, picture: require('../assets/images/Builder_Hut.png')},
  ],
  [BUILDING_TYPES.TOWN_HALL]: [
    {level: 1, cost: 0, resource: GOLD, time: 0, picture: require('../assets/images/Town_Hall1.png')},
    {level: 2, cost: 1 * K, resource: GOLD, time: 10 * SECONDS, picture: require('../assets/images/Town_Hall2.png')},
    {level: 3, cost: 4 * K, resource: GOLD, time: 3 * HOURS, picture: require('../assets/images/Town_Hall3.png')},
    {level: 4, cost: 25 * K, resource: GOLD, time: 1 * DAYS, picture: require('../assets/images/Town_Hall4.png')},
    {level: 5, cost: 150 * K, resource: GOLD, time: 2 * DAYS, picture: require('../assets/images/Town_Hall5.png')},
    {level: 6, cost: 750 * K, resource: GOLD, time: 4 * DAYS, picture: require('../assets/images/Town_Hall6.png')},
    {level: 7, cost: 1.2 * M, resource: GOLD, time: 6 * DAYS, picture: require('../assets/images/Town_Hall7.png')},
    {level: 8, cost: 2 * M, resource: GOLD, time: 8 * DAYS, picture: require('../assets/images/Town_Hall8.png')},
    {level: 9, cost: 3 * M, resource: GOLD, time: 10 * DAYS, picture: require('../assets/images/Town_Hall9.png')},
    {level: 10, cost: 5 * M, resource: GOLD, time: 12 * DAYS, picture: require('../assets/images/Town_Hall10.png')},
    {level: 11, cost: 7 * M, resource: GOLD, time: 14 * DAYS, picture: require('../assets/images/Town_Hall11.png')},
    {level: 12, cost: 9.5 * M, resource: GOLD, time: 14 * DAYS, picture: require('../assets/images/Town_Hall12.png')},
  ],
  [BUILDING_TYPES.DEFENSES.CANON]: [
    {level: 1, cost: 250, resource: GOLD, time: 10 * SECONDS, requiredTH: 1, picture: require('../assets/images/Cannon1.png')},
    {level: 2, cost: 1 * K, resource: GOLD, time: 15 * MINUTES, requiredTH: 1, picture: require('../assets/images/Cannon2.png')},
    {level: 3, cost: 4 * K, resource: GOLD, time: 45 * MINUTES, requiredTH: 2, picture: require('../assets/images/Cannon3.png')},
    {level: 4, cost: 16 * K, resource: GOLD, time: 1 * HOURS, requiredTH: 3, picture: require('../assets/images/Cannon4.png')},
    {level: 5, cost: 50 * K, resource: GOLD, time: 4 * HOURS, requiredTH: 4, picture: require('../assets/images/Cannon5.png')},
    {level: 6, cost: 100 * K, resource: GOLD, time: 8 * HOURS, requiredTH: 5, picture: require('../assets/images/Cannon6.png')},
    {level: 7, cost: 200 * K, resource: GOLD, time: 16 * HOURS, requiredTH: 6, picture: require('../assets/images/Cannon7.png')},
    {level: 8, cost: 400 * K, resource: GOLD, time: 1 * DAYS + 12 * HOURS, requiredTH: 7, picture: require('../assets/images/Cannon8.png')},
    {level: 9, cost: 800 * K, resource: GOLD, time: 2 * DAYS, requiredTH: 8, picture: require('../assets/images/Cannon9.png')},
    {level: 10, cost: 1.5 * M, resource: GOLD, time: 2 * DAYS + 12 * HOURS, requiredTH: 8, picture: require('../assets/images/Cannon10.png')},
    {level: 11, cost: 3 * M, resource: GOLD, time: 3 * DAYS, requiredTH: 9, picture: require('../assets/images/Cannon11.png')},
    {level: 12, cost: 4.5 * M, resource: GOLD, time: 3 * DAYS + 12 * HOURS, requiredTH: 10, picture: require('../assets/images/Cannon12.png')},
    {level: 13, cost: 6 * M, resource: GOLD, time: 4 * DAYS, requiredTH: 10, picture: require('../assets/images/Cannon13.png')},
    {level: 14, cost: 7.5 * M, resource: GOLD, time: 5 * DAYS, requiredTH: 11, picture: require('../assets/images/Cannon14.png')},
    {level: 15, cost: 9 * M, resource: GOLD, time: 6 * DAYS, requiredTH: 11, picture: require('../assets/images/Cannon15.png')},
    {level: 16, cost: 11 * M, resource: GOLD, time: 10 * DAYS, requiredTH: 12, picture: require('../assets/images/Cannon16.png')},
  ],
  [BUILDING_TYPES.DEFENSES.ARCHER_TOWER]: [
    {level: 1, cost: 1000, resource: GOLD, time: 1 * MINUTES, requiredTH: 2, picture: require('../assets/images/Archer_Tower1.png')},
    {level: 2, cost: 2 * K, resource: GOLD, time: 30 * MINUTES, requiredTH: 2, picture: require('../assets/images/Archer_Tower2.png')},
    {level: 3, cost: 5 * K, resource: GOLD, time: 45 * MINUTES, requiredTH: 3, picture: require('../assets/images/Archer_Tower3.png')},
    {level: 4, cost: 20 * K, resource: GOLD, time: 3 * HOURS, requiredTH: 4, picture: require('../assets/images/Archer_Tower4.png')},
    {level: 5, cost: 80 * K, resource: GOLD, time: 8 * HOURS, requiredTH: 5, picture: require('../assets/images/Archer_Tower5.png')},
    {level: 6, cost: 180 * K, resource: GOLD, time: 12 * HOURS, requiredTH: 5, picture: require('../assets/images/Archer_Tower6.png')},
    {level: 7, cost: 360 * K, resource: GOLD, time: 1 * DAYS + 12 * HOURS, requiredTH: 6, picture: require('../assets/images/Archer_Tower7.png')},
    {level: 8, cost: 720 * K, resource: GOLD, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Archer_Tower8.png')},
    {level: 9, cost: 1 * M, resource: GOLD, time: 2 * DAYS + 12 * HOURS, requiredTH: 8, picture: require('../assets/images/Archer_Tower9.png')},
    {level: 10, cost: 2 * M, resource: GOLD, time: 3 * DAYS, requiredTH: 8, picture: require('../assets/images/Archer_Tower10.png')},
    {level: 11, cost: 3.5 * M, resource: GOLD, time: 3 * DAYS + 12 * HOURS, requiredTH: 9, picture: require('../assets/images/Archer_Tower11.png')},
    {level: 12, cost: 5 * M, resource: GOLD, time: 4 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Tower12.png')},
    {level: 13, cost: 6.5 * M, resource: GOLD, time: 5 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Tower13.png')},
    {level: 14, cost: 8 * M, resource: GOLD, time: 6 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Tower14.png')},
    {level: 15, cost: 9.5 * M, resource: GOLD, time: 8 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Tower15.png')},
    {level: 16, cost: 11 * M, resource: GOLD, time: 11 * DAYS, requiredTH: 12, picture: require('../assets/images/Archer_Tower16.png')},
  ],
  [BUILDING_TYPES.DEFENSES.MORTAR]: [
    {level: 1, cost: 8 * K, resource: GOLD, time: 5 * HOURS, requiredTH: 3, picture: require('../assets/images/Mortar1.png')},
    {level: 2, cost: 32 * K, resource: GOLD, time: 8 * HOURS, requiredTH: 4, picture: require('../assets/images/Mortar2.png')},
    {level: 3, cost: 120 * K, resource: GOLD, time: 16 * HOURS, requiredTH: 5, picture: require('../assets/images/Mortar3.png')},
    {level: 4, cost: 400 * K, resource: GOLD, time: 1 * DAYS + 12 * HOURS, requiredTH: 6, picture: require('../assets/images/Mortar4.png')},
    {level: 5, cost: 800 * K, resource: GOLD, time: 2 * DAYS + 12 * HOURS, requiredTH: 7, picture: require('../assets/images/Mortar5.png')},
    {level: 6, cost: 1.6 * M, resource: GOLD, time: 3 * DAYS, requiredTH: 8, picture: require('../assets/images/Mortar6.png')},
    {level: 7, cost: 3.2 * M, resource: GOLD, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Mortar7.png')},
    {level: 8, cost: 5 * M, resource: GOLD, time: 5 * DAYS, requiredTH: 10, picture: require('../assets/images/Mortar8.png')},
    {level: 9, cost: 7 * M, resource: GOLD, time: 6 * DAYS, requiredTH: 11, picture: require('../assets/images/Mortar9.png')},
    {level: 10, cost: 9 * M, resource: GOLD, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Mortar10.png')},
    {level: 11, cost: 11 * M, resource: GOLD, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Mortar11.png')},
  ],
  [BUILDING_TYPES.DEFENSES.AIR_DEFENSE]: [
    {level: 1, cost: 22.5 * K, resource: GOLD, time: 3 * HOURS, requiredTH: 4, picture: require('../assets/images/Air_Defense1.png')},
    {level: 2, cost: 90 * K, resource: GOLD, time: 12 * HOURS, requiredTH: 4, picture: require('../assets/images/Air_Defense2.png')},
    {level: 3, cost: 270 * K, resource: GOLD, time: 2 * DAYS, requiredTH: 5, picture: require('../assets/images/Air_Defense3.png')},
    {level: 4, cost: 500 * K, resource: GOLD, time: 2 * DAYS + 12 * HOURS, requiredTH: 6, picture: require('../assets/images/Air_Defense4.png')},
    {level: 5, cost: 1 * M, resource: GOLD, time: 3 * DAYS + 12 * HOURS, requiredTH: 7, picture: require('../assets/images/Air_Defense5.png')},
    {level: 6, cost: 2 * M, resource: GOLD, time: 4 * DAYS, requiredTH: 8, picture: require('../assets/images/Air_Defense6.png')},
    {level: 7, cost: 4 * M, resource: GOLD, time: 5 * DAYS, requiredTH: 9, picture: require('../assets/images/Air_Defense7.png')},
    {level: 8, cost: 6.3 * M, resource: GOLD, time: 6 * DAYS, requiredTH: 10, picture: require('../assets/images/Air_Defense8.png')},
    {level: 9, cost: 8.8 * M, resource: GOLD, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Air_Defense9.png')},
    {level: 10, cost: 10.8 * M, resource: GOLD, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Air_Defense10.png')},
  ],
  [BUILDING_TYPES.DEFENSES.WIZARD_TOWER]: [
    {level: 1, cost: 180 * K, resource: GOLD, time: 8 * HOURS, requiredTH: 5, picture: require('../assets/images/Wizard_Tower1.png')},
    {level: 2, cost: 360 * K, resource: GOLD, time: 12 * HOURS, requiredTH: 5, picture: require('../assets/images/Wizard_Tower2.png')},
    {level: 3, cost: 700 * K, resource: GOLD, time: 1.5 * DAYS, requiredTH: 6, picture: require('../assets/images/Wizard_Tower3.png')},
    {level: 4, cost: 1.2 * M, resource: GOLD, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Wizard_Tower4.png')},
    {level: 5, cost: 1.7 * M, resource: GOLD, time: 2.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Wizard_Tower5.png')},
    {level: 6, cost: 2.2 * M, resource: GOLD, time: 3 * DAYS, requiredTH: 8, picture: require('../assets/images/Wizard_Tower6.png')},
    {level: 7, cost: 3.7 * M, resource: GOLD, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Wizard_Tower7.png')},
    {level: 8, cost: 5.2 * M, resource: GOLD, time: 5.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Wizard_Tower8.png')},
    {level: 9, cost: 7.2 * M, resource: GOLD, time: 7 * DAYS, requiredTH: 10, picture: require('../assets/images/Wizard_Tower9.png')},
    {level: 10, cost: 9.2 * M, resource: GOLD, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Wizard_Tower10.png')},
    {level: 11, cost: 11.2 * M, resource: GOLD, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Wizard_Tower11.png')},
  ],
  [BUILDING_TYPES.DEFENSES.AIR_SWEEPER]: [
    {level: 1, cost: 500 * K, resource: GOLD, time: 12 * HOURS, requiredTH: 6, picture: require('../assets/images/Air_Sweeper1.png')},
    {level: 2, cost: 750 * K, resource: GOLD, time: 2 * DAYS, requiredTH: 6, picture: require('../assets/images/Air_Sweeper2.png')},
    {level: 3, cost: 1.25 * M, resource: GOLD, time: 3.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Air_Sweeper3.png')},
    {level: 4, cost: 2.4 * M, resource: GOLD, time: 4.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Air_Sweeper4.png')},
    {level: 5, cost: 4.8 * M, resource: GOLD, time: 5.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Air_Sweeper5.png')},
    {level: 6, cost: 7.2 * M, resource: GOLD, time: 6 * DAYS, requiredTH: 10, picture: require('../assets/images/Air_Sweeper6.png')},
    {level: 7, cost: 9.6 * M, resource: GOLD, time: 6.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Air_Sweeper7.png')},
  ],
  [BUILDING_TYPES.DEFENSES.TESLA]: [
    {level: 1, cost: 1 * M, resource: GOLD, time: 12 * HOURS, requiredTH: 7, picture: require('../assets/images/Hidden_Tesla1.png')},
    {level: 2, cost: 1.25 * M, resource: GOLD, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Hidden_Tesla2.png')},
    {level: 3, cost: 1.5 * M, resource: GOLD, time: 3.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Hidden_Tesla3.png')},
    {level: 4, cost: 2 * M, resource: GOLD, time: 4 * DAYS, requiredTH: 8, picture: require('../assets/images/Hidden_Tesla4.png')},
    {level: 5, cost: 2.5 * M, resource: GOLD, time: 4.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Hidden_Tesla5.png')},
    {level: 6, cost: 3 * M, resource: GOLD, time: 5.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Hidden_Tesla6.png')},
    {level: 7, cost: 3.5 * M, resource: GOLD, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Hidden_Tesla7.png')},
    {level: 8, cost: 5 * M, resource: GOLD, time: 8 * DAYS, requiredTH: 10, picture: require('../assets/images/Hidden_Tesla8.png')},
    {level: 9, cost: 8 * M, resource: GOLD, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Hidden_Tesla9.png')},
    {level: 10, cost: 10 * M, resource: GOLD, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Hidden_Tesla10.png')},
  ],
  [BUILDING_TYPES.DEFENSES.BOMB_TOWER]: [
    {level: 1, cost: 2 * M, resource: GOLD, time: 2.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Bomb_Tower1.png')},
    {level: 2, cost: 3.5 * M, resource: GOLD, time: 4 * DAYS, requiredTH: 8, picture: require('../assets/images/Bomb_Tower2.png')},
    {level: 3, cost: 5 * M, resource: GOLD, time: 6 * DAYS, requiredTH: 9, picture: require('../assets/images/Bomb_Tower3.png')},
    {level: 4, cost: 7 * M, resource: GOLD, time: 7 * DAYS, requiredTH: 10, picture: require('../assets/images/Bomb_Tower4.png')},
    {level: 5, cost: 9 * M, resource: GOLD, time: 9 * DAYS, requiredTH: 11, picture: require('../assets/images/Bomb_Tower5.png')},
    {level: 6, cost: 10 * M, resource: GOLD, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Bomb_Tower6.png')},
    {level: 7, cost: 11 * M, resource: GOLD, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Bomb_Tower7.png')},
  ],
  [BUILDING_TYPES.DEFENSES.XBOW]: [
    {level: 1, cost: 3 * M, resource: GOLD, time: 4.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Xbow_Air1.png')},
    {level: 2, cost: 4 * M, resource: GOLD, time: 5.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Xbow_Air2.png')},
    {level: 3, cost: 5 * M, resource: GOLD, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Xbow_Air3.png')},
    {level: 4, cost: 7 * M, resource: GOLD, time: 8 * DAYS, requiredTH: 10, picture: require('../assets/images/Xbow_Air4.png')},
    {level: 5, cost: 9.5 * M, resource: GOLD, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Xbow_Air5.png')},
    {level: 6, cost: 12 * M, resource: GOLD, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Xbow_Air6.png')},
  ],
  [BUILDING_TYPES.DEFENSES.INFERNO_TOWER]: [
    {level: 1, cost: 5 * M, resource: GOLD, time: 4.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Inferno_Tower_Multi1.png')},
    {level: 2, cost: 6 * M, resource: GOLD, time: 5.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Inferno_Tower_Multi2.png')},
    {level: 3, cost: 7 * M, resource: GOLD, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Inferno_Tower_Multi3.png')},
    {level: 4, cost: 9 * M, resource: GOLD, time: 8 * DAYS, requiredTH: 11, picture: require('../assets/images/Inferno_Tower_Multi4.png')},
    {level: 5, cost: 10 * M, resource: GOLD, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Inferno_Tower_Multi5.png')},
    {level: 6, cost: 11 * M, resource: GOLD, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Inferno_Tower_Multi6.png')},
  ],
  [BUILDING_TYPES.DEFENSES.EAGLE_ARTILLERY]: [
    {level: 1, cost: 8 * M, resource: GOLD, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Eagle_Artillery1.png')},
    {level: 2, cost: 10 * M, resource: GOLD, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Eagle_Artillery2.png')},
    {level: 3, cost: 12 * M, resource: GOLD, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Eagle_Artillery3.png')},
  ],
  [BUILDING_TYPES.DEFENSES.GIGA_TESLA]: [
    {level: 1, cost: 0, resource: GOLD, time: 0, requiredTH: 12, picture: require('../assets/images/Giga_Tesla1.png')},
    {level: 2, cost: 6 * M, resource: GOLD, time: 2 * DAYS, requiredTH: 12, picture: require('../assets/images/Giga_Tesla2.png')},
    {level: 3, cost: 8 * M, resource: GOLD, time: 4 * DAYS, requiredTH: 12, picture: require('../assets/images/Giga_Tesla3.png')},
    {level: 4, cost: 10 * M, resource: GOLD, time: 6 * DAYS, requiredTH: 12, picture: require('../assets/images/Giga_Tesla4.png')},
    {level: 5, cost: 12 * M, resource: GOLD, time: 8 * DAYS, requiredTH: 12, picture: require('../assets/images/Giga_Tesla5.png')},
  ],
  //**END DEFENSES**/

  //**TROOPS**//
  [BUILDING_TYPES.TROOPS.BARBARIAN]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Barbarian1.png')},
    {level: 2, cost: 50 * K, resource: ELIXIR, time: 6 * HOURS, requiredTH: 3, picture: require('../assets/images/Barbarian1.png')},
    {level: 3, cost: 150 * K, resource: ELIXIR, time: 1 * DAYS, requiredTH: 5, picture: require('../assets/images/Barbarian3.png')},
    {level: 4, cost: 500 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Barbarian3.png')},
    {level: 5, cost: 1.5 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Barbarian5.png')},
    {level: 6, cost: 4.5 * M, resource: ELIXIR, time: 4.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian6.png')},
    {level: 7, cost: 6 * M, resource: ELIXIR, time: 7.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Barbarian7.png')},
    {level: 8, cost: 8 * M, resource: ELIXIR, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Barbarian8.png')},
  ],
  [BUILDING_TYPES.TROOPS.ARCHER]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Archer1.png')},
    {level: 2, cost: 50 * K, resource: ELIXIR, time: 12 * HOURS, requiredTH: 3, picture: require('../assets/images/Archer1.png')},
    {level: 3, cost: 250 * K, resource: ELIXIR, time: 1 * DAYS, requiredTH: 5, picture: require('../assets/images/Archer3.png')},
    {level: 4, cost: 750 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Archer3.png')},
    {level: 5, cost: 2.25 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Archer5.png')},
    {level: 6, cost: 6 * M, resource: ELIXIR, time: 4.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer6.png')},
    {level: 7, cost: 7.5 * M, resource: ELIXIR, time: 7.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer7.png')},
    {level: 8, cost: 9 * M, resource: ELIXIR, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer8.png')},
  ],
  [BUILDING_TYPES.TROOPS.GIANT]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Giant1.png')},
    {level: 2, cost: 100 * K, resource: ELIXIR, time: 12 * HOURS, requiredTH: 4, picture: require('../assets/images/Giant1.png')},
    {level: 3, cost: 250 * K, resource: ELIXIR, time: 1.5 * DAYS, requiredTH: 6, picture: require('../assets/images/Giant3.png')},
    {level: 4, cost: 750 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Giant3.png')},
    {level: 5, cost: 2.25 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Giant5.png')},
    {level: 6, cost: 5 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Giant6.png')},
    {level: 7, cost: 6 * M, resource: ELIXIR, time: 8 * DAYS, requiredTH: 10, picture: require('../assets/images/Giant7.png')},
    {level: 8, cost: 9.5 * M, resource: ELIXIR, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Giant8.png')},
    {level: 9, cost: 12 * M, resource: ELIXIR, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Giant9.png')},
  ],
  [BUILDING_TYPES.TROOPS.GOBLIN]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Goblin1.png')},
    {level: 2, cost: 50 * K, resource: ELIXIR, time: 12 * HOURS, requiredTH: 3, picture: require('../assets/images/Goblin1.png')},
    {level: 3, cost: 250 * K, resource: ELIXIR, time: 1.5 * DAYS, requiredTH: 5, picture: require('../assets/images/Goblin3.png')},
    {level: 4, cost: 750 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Goblin3.png')},
    {level: 5, cost: 2.25 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Goblin5.png')},
    {level: 6, cost: 4.5 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Goblin6.png')},
    {level: 7, cost: 6.75 * M, resource: ELIXIR, time: 10 * DAYS, requiredTH: 10, picture: require('../assets/images/Goblin7.png')},
  ],
  [BUILDING_TYPES.TROOPS.WALL_BREAKER]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Wall_Breaker1.png')},
    {level: 2, cost: 100 * K, resource: ELIXIR, time: 12 * HOURS, requiredTH: 4, picture: require('../assets/images/Wall_Breaker1.png')},
    {level: 3, cost: 250 * K, resource: ELIXIR, time: 1.5 * DAYS, requiredTH: 6, picture: require('../assets/images/Wall_Breaker3.png')},
    {level: 4, cost: 750 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Wall_Breaker3.png')},
    {level: 5, cost: 2 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Wall_Breaker5.png')},
    {level: 6, cost: 6 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Wall_Breaker6.png')},
    {level: 7, cost: 9 * M, resource: ELIXIR, time: 8 * DAYS, requiredTH: 11, picture: require('../assets/images/Wall_Breaker7.png')},
    {level: 8, cost: 12 * M, resource: ELIXIR, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Wall_Breaker7.png')},
  ],
  [BUILDING_TYPES.TROOPS.BALLOON]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Balloon1.png')},
    {level: 2, cost: 150 * K, resource: ELIXIR, time: 12 * HOURS, requiredTH: 4, picture: require('../assets/images/Balloon1.png')},
    {level: 3, cost: 450 * K, resource: ELIXIR, time: 1.5 * DAYS, requiredTH: 6, picture: require('../assets/images/Balloon3.png')},
    {level: 4, cost: 1.35 * M, resource: ELIXIR, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Balloon3.png')},
    {level: 5, cost: 2.5 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Balloon5.png')},
    {level: 6, cost: 6 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Balloon6.png')},
    {level: 7, cost: 9.5 * M, resource: ELIXIR, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Balloon7.png')},
    {level: 8, cost: 12 * M, resource: ELIXIR, time: 12 * DAYS, requiredTH: 12, picture: require('../assets/images/Balloon8.png')},
  ],
  [BUILDING_TYPES.TROOPS.WIZARD]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Wizard1.png')},
    {level: 2, cost: 150 * K, resource: ELIXIR, time: 12 * HOURS, requiredTH: 5, picture: require('../assets/images/Wizard1.png')},
    {level: 3, cost: 450 * K, resource: ELIXIR, time: 1.5 * DAYS, requiredTH: 6, picture: require('../assets/images/Wizard3.png')},
    {level: 4, cost: 1.35 * M, resource: ELIXIR, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Wizard3.png')},
    {level: 5, cost: 2.5 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Wizard5.png')},
    {level: 6, cost: 5 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Wizard6.png')},
    {level: 7, cost: 7 * M, resource: ELIXIR, time: 11.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Wizard7.png')},
    {level: 8, cost: 9 * M, resource: ELIXIR, time: 12 * DAYS, requiredTH: 11, picture: require('../assets/images/Wizard8.png')},
    {level: 9, cost: 11 * M, resource: ELIXIR, time: 12 * DAYS, requiredTH: 12, picture: require('../assets/images/Wizard9.png')},
  ],
  [BUILDING_TYPES.TROOPS.HEALER]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Healer1.png')},
    {level: 2, cost: 750 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Healer1.png')},
    {level: 3, cost: 1.5 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Healer3.png')},
    {level: 4, cost: 3 * M, resource: ELIXIR, time: 6 * DAYS, requiredTH: 9, picture: require('../assets/images/Healer4.png')},
    {level: 5, cost: 9.5 * M, resource: ELIXIR, time: 14 * DAYS, requiredTH: 11, picture: require('../assets/images/Healer5.png')},
  ],
  [BUILDING_TYPES.TROOPS.DRAGON]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Dragon1.png')},
    {level: 2, cost: 2 * M, resource: ELIXIR, time: 4.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Dragon2.png')},
    {level: 3, cost: 3 * M, resource: ELIXIR, time: 6 * DAYS, requiredTH: 8, picture: require('../assets/images/Dragon3.png')},
    {level: 4, cost: 5 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Dragon4.png')},
    {level: 5, cost: 7 * M, resource: ELIXIR, time: 8 * DAYS, requiredTH: 10, picture: require('../assets/images/Dragon5.png')},
    {level: 6, cost: 9 * M, resource: ELIXIR, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Dragon6.png')},
    {level: 7, cost: 11 * M, resource: ELIXIR, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Dragon7.png')},
  ],
  [BUILDING_TYPES.TROOPS.PEKKA]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/PEKKA1.png')},
    {level: 2, cost: 3 * M, resource: ELIXIR, time: 4.5 * DAYS, requiredTH: 8, picture: require('../assets/images/PEKKA2.png')},
    {level: 3, cost: 5 * M, resource: ELIXIR, time: 5.5 * DAYS, requiredTH: 8, picture: require('../assets/images/PEKKA3.png')},
    {level: 4, cost: 6 * M, resource: ELIXIR, time: 6 * DAYS, requiredTH: 9, picture: require('../assets/images/PEKKA4.png')},
    {level: 5, cost: 7.5 * M, resource: ELIXIR, time: 7.5 * DAYS, requiredTH: 10, picture: require('../assets/images/PEKKA5.png')},
    {level: 6, cost: 8.5 * M, resource: ELIXIR, time: 8.5 * DAYS, requiredTH: 10, picture: require('../assets/images/PEKKA6.png')},
    {level: 7, cost: 10 * M, resource: ELIXIR, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/PEKKA7.png')},
    {level: 8, cost: 12 * M, resource: ELIXIR, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/PEKKA7.png')},
  ],
  [BUILDING_TYPES.TROOPS.BABY_DRAGON]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Baby_Dragon1.png')},
    {level: 2, cost: 5 * M, resource: ELIXIR, time: 5.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Baby_Dragon1.png')},
    {level: 3, cost: 6 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Baby_Dragon3.png')},
    {level: 4, cost: 7 * M, resource: ELIXIR, time: 8 * DAYS, requiredTH: 10, picture: require('../assets/images/Baby_Dragon4.png')},
    {level: 5, cost: 8 * M, resource: ELIXIR, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Baby_Dragon5.png')},
    {level: 6, cost: 9 * M, resource: ELIXIR, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Baby_Dragon6.png')},
  ],
  [BUILDING_TYPES.TROOPS.MINER]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Miner1.png')},
    {level: 2, cost: 6 * M, resource: ELIXIR, time: 5.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Miner1.png')},
    {level: 3, cost: 7 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Miner3.png')},
    {level: 4, cost: 8 * M, resource: ELIXIR, time: 8 * DAYS, requiredTH: 10, picture: require('../assets/images/Miner3.png')},
    {level: 5, cost: 9.5 * M, resource: ELIXIR, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Miner5.png')},
    {level: 6, cost: 11 * M, resource: ELIXIR, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Miner5.png')},
  ],
  [BUILDING_TYPES.TROOPS.ELECTRO_DRAGON]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Electro_Dragon1.png')},
    {level: 2, cost: 9 * M, resource: ELIXIR, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Electro_Dragon1.png')},
    {level: 3, cost: 11 * M, resource: ELIXIR, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Electro_Dragon1.png')},
  ],
  //**END TROOPS**//
  //**DARK_TROOPS**//
  [BUILDING_TYPES.DARK_TROOPS.MINION]: [
    {level: 1, cost: 0, resource: BLACK, time: 0, requiredTH: 1, picture: require('../assets/images/Minion1.png')},
    {level: 2, cost: 10 * K, resource: BLACK, time: 3.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Minion1.png')},
    {level: 3, cost: 20 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 8, picture: require('../assets/images/Minion3.png')},
    {level: 4, cost: 30 * K, resource: BLACK, time: 4.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Minion3.png')},
    {level: 5, cost: 40 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Minion5.png')},
    {level: 6, cost: 100 * K, resource: BLACK, time: 8 * DAYS, requiredTH: 10, picture: require('../assets/images/Minion6.png')},
    {level: 7, cost: 140 * K, resource: BLACK, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Minion7.png')},
    {level: 8, cost: 180 * K, resource: BLACK, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Minion7.png')},
  ],
  [BUILDING_TYPES.DARK_TROOPS.HOG_RIDER]: [
    {level: 1, cost: 0, resource: BLACK, time: 0, requiredTH: 1, picture: require('../assets/images/Hog_Rider1.png')},
    {level: 2, cost: 20 * K, resource: BLACK, time: 3.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Hog_Rider1.png')},
    {level: 3, cost: 30 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 8, picture: require('../assets/images/Hog_Rider3.png')},
    {level: 4, cost: 40 * K, resource: BLACK, time: 4.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Hog_Rider3.png')},
    {level: 5, cost: 50 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Hog_Rider5.png')},
    {level: 6, cost: 100 * K, resource: BLACK, time: 8 * DAYS, requiredTH: 10, picture: require('../assets/images/Hog_Rider6.png')},
    {level: 7, cost: 150 * K, resource: BLACK, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Hog_Rider7.png')},
    {level: 8, cost: 200 * K, resource: BLACK, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Hog_Rider8.png')},
  ],
  [BUILDING_TYPES.DARK_TROOPS.VALKYRIE]: [
    {level: 1, cost: 0, resource: BLACK, time: 0, requiredTH: 1, picture: require('../assets/images/Valkyrie1.png')},
    {level: 2, cost: 50 * K, resource: BLACK, time: 5.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Valkyrie1.png')},
    {level: 3, cost: 60 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Valkyrie3.png')},
    {level: 4, cost: 70 * K, resource: BLACK, time: 8 * DAYS, requiredTH: 9, picture: require('../assets/images/Valkyrie3.png')},
    {level: 5, cost: 110 * K, resource: BLACK, time: 9.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Valkyrie5.png')},
    {level: 6, cost: 150 * K, resource: BLACK, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Valkyrie6.png')},
    {level: 7, cost: 190 * K, resource: BLACK, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Valkyrie6.png')},
  ],
  [BUILDING_TYPES.DARK_TROOPS.GOLEM]: [
    {level: 1, cost: 0, resource: BLACK, time: 0, requiredTH: 1, picture: require('../assets/images/Golem1.png')},
    {level: 2, cost: 60 * K, resource: BLACK, time: 3 * DAYS, requiredTH: 8, picture: require('../assets/images/Golem1.png')},
    {level: 3, cost: 70 * K, resource: BLACK, time: 5.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Golem3.png')},
    {level: 4, cost: 80 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Golem3.png')},
    {level: 5, cost: 90 * K, resource: BLACK, time: 8 * DAYS, requiredTH: 10, picture: require('../assets/images/Golem5.png')},
    {level: 6, cost: 150 * K, resource: BLACK, time: 9.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Golem6.png')},
    {level: 7, cost: 200 * K, resource: BLACK, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Golem7.png')},
    {level: 8, cost: 200 * K, resource: BLACK, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Golem8.png')},
  ],
  [BUILDING_TYPES.DARK_TROOPS.WITCH]: [
    {level: 1, cost: 0, resource: BLACK, time: 0, requiredTH: 1, picture: require('../assets/images/Witch1.png')},
    {level: 2, cost: 75 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Witch1.png')},
    {level: 3, cost: 160 * K, resource: BLACK, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Witch3.png')},
    {level: 4, cost: 200 * K, resource: BLACK, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Witch3.png')},
  ],
  [BUILDING_TYPES.DARK_TROOPS.LAVA_HOUND]: [
    {level: 1, cost: 0, resource: BLACK, time: 0, requiredTH: 1, picture: require('../assets/images/Lava_Hound1.png')},
    {level: 2, cost: 60 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Lava_Hound1.png')},
    {level: 3, cost: 70 * K, resource: BLACK, time: 8 * DAYS, requiredTH: 10, picture: require('../assets/images/Lava_Hound3.png')},
    {level: 4, cost: 150 * K, resource: BLACK, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Lava_Hound4.png')},
    {level: 5, cost: 200 * K, resource: BLACK, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Lava_Hound5.png')},
  ],
  [BUILDING_TYPES.DARK_TROOPS.BOWLER]: [
    {level: 1, cost: 0, resource: BLACK, time: 0, requiredTH: 1, picture: require('../assets/images/Bowler1.png')},
    {level: 2, cost: 120 * K, resource: BLACK, time: 8.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Bowler1.png')},
    {level: 3, cost: 200 * K, resource: BLACK, time: 14 * DAYS, requiredTH: 11, picture: require('../assets/images/Bowler3.png')},
    {level: 4, cost: 200 * K, resource: BLACK, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Bowler4.png')},
  ],
  //**END DARK_TROOPS**//
  //**SPELLS**//
  [BUILDING_TYPES.SPELLS.LIGHTNING]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Lightning_Spell.png')},
    {level: 2, cost: 200 * K, resource: ELIXIR, time: 1 * DAYS, requiredTH: 3, picture: require('../assets/images/Lightning_Spell.png')},
    {level: 3, cost: 500 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 4, picture: require('../assets/images/Lightning_Spell.png')},
    {level: 4, cost: 1 * M, resource: ELIXIR, time: 3 * DAYS, requiredTH: 5, picture: require('../assets/images/Lightning_Spell.png')},
    {level: 5, cost: 2 * M, resource: ELIXIR, time: 4 * DAYS, requiredTH: 8, picture: require('../assets/images/Lightning_Spell.png')},
    {level: 6, cost: 6 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Lightning_Spell.png')},
    {level: 7, cost: 8 * M, resource: ELIXIR, time: 14 * DAYS, requiredTH: 10, picture: require('../assets/images/Lightning_Spell.png')},
  ],
  [BUILDING_TYPES.SPELLS.HEALING]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Healing_Spell.png')},
    {level: 2, cost: 300 * K, resource: ELIXIR, time: 1 * DAYS, requiredTH: 4, picture: require('../assets/images/Healing_Spell.png')},
    {level: 3, cost: 600 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 6, picture: require('../assets/images/Healing_Spell.png')},
    {level: 4, cost: 1.2 * M, resource: ELIXIR, time: 3 * DAYS, requiredTH: 7, picture: require('../assets/images/Healing_Spell.png')},
    {level: 5, cost: 2 * M, resource: ELIXIR, time: 5 * DAYS, requiredTH: 8, picture: require('../assets/images/Healing_Spell.png')},
    {level: 6, cost: 4 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 9, picture: require('../assets/images/Healing_Spell.png')},
    {level: 7, cost: 6 * M, resource: ELIXIR, time: 10 * DAYS, requiredTH: 10, picture: require('../assets/images/Healing_Spell.png')},
  ],
  [BUILDING_TYPES.SPELLS.RAGE]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Rage_Spell.png')},
    {level: 2, cost: 450 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 5, picture: require('../assets/images/Rage_Spell.png')},
    {level: 3, cost: 900 * K, resource: ELIXIR, time: 3 * DAYS, requiredTH: 6, picture: require('../assets/images/Rage_Spell.png')},
    {level: 4, cost: 1.8 * M, resource: ELIXIR, time: 5 * DAYS, requiredTH: 7, picture: require('../assets/images/Rage_Spell.png')},
    {level: 5, cost: 3 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 8, picture: require('../assets/images/Rage_Spell.png')},
  ],
  [BUILDING_TYPES.SPELLS.JUMP]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Jump_Spell.png')},
    {level: 2, cost: 3 * M, resource: ELIXIR, time: 5 * DAYS, requiredTH: 7, picture: require('../assets/images/Jump_Spell.png')},
    {level: 3, cost: 6 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 10, picture: require('../assets/images/Jump_Spell.png')},
  ],
  [BUILDING_TYPES.SPELLS.FREEZE]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Freeze_Spell.png')},
    {level: 2, cost: 3 * M, resource: ELIXIR, time: 3 * DAYS, requiredTH: 10, picture: require('../assets/images/Freeze_Spell.png')},
    {level: 3, cost: 4 * M, resource: ELIXIR, time: 4.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Freeze_Spell.png')},
    {level: 4, cost: 5 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Freeze_Spell.png')},
    {level: 5, cost: 7 * M, resource: ELIXIR, time: 8 * DAYS, requiredTH: 10, picture: require('../assets/images/Freeze_Spell.png')},
    {level: 6, cost: 9.5 * M, resource: ELIXIR, time: 9 * DAYS, requiredTH: 11, picture: require('../assets/images/Freeze_Spell.png')},
    {level: 7, cost: 11 * M, resource: ELIXIR, time: 11.5 * DAYS, requiredTH: 12, picture: require('../assets/images/Freeze_Spell.png')},
  ],
  [BUILDING_TYPES.SPELLS.CLONE]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Clone_Spell.png')},
    {level: 2, cost: 4 * M, resource: ELIXIR, time: 4 * DAYS, requiredTH: 10, picture: require('../assets/images/Clone_Spell.png')},
    {level: 3, cost: 6 * M, resource: ELIXIR, time: 5 * DAYS, requiredTH: 10, picture: require('../assets/images/Clone_Spell.png')},
    {level: 4, cost: 8 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Clone_Spell.png')},
    {level: 5, cost: 10 * M, resource: ELIXIR, time: 11.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Clone_Spell.png')},
  ],
  //**END SPELLS**//
  //**DARK_SPELLS**//
  [BUILDING_TYPES.DARK_SPELLS.POISON]: [
    {level: 1, cost: 0, resource: BLACK, time: 0, requiredTH: 1, picture: require('../assets/images/Poison_Spell.png')},
    {level: 2, cost: 25 * K, resource: BLACK, time: 2.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Poison_Spell.png')},
    {level: 3, cost: 50 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Poison_Spell.png')},
    {level: 4, cost: 75 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Poison_Spell.png')},
    {level: 5, cost: 150 * K, resource: BLACK, time: 9.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Poison_Spell.png')},
  ],
  [BUILDING_TYPES.DARK_SPELLS.EARTHQUAKE]: [
    {level: 1, cost: 0, resource: BLACK, time: 0, requiredTH: 1, picture: require('../assets/images/Earthquake_Spell.png')},
    {level: 2, cost: 30 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 8, picture: require('../assets/images/Earthquake_Spell.png')},
    {level: 3, cost: 80 * K, resource: BLACK, time: 5 * DAYS, requiredTH: 9, picture: require('../assets/images/Earthquake_Spell.png')},
    {level: 4, cost: 90 * K, resource: BLACK, time: 9.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Earthquake_Spell.png')},
  ],
  [BUILDING_TYPES.DARK_SPELLS.HASTE]: [
    {level: 1, cost: 0, resource: BLACK, time: 0, requiredTH: 1, picture: require('../assets/images/Haste_Spell.png')},
    {level: 2, cost: 40 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Haste_Spell.png')},
    {level: 3, cost: 80 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Haste_Spell.png')},
    {level: 4, cost: 100 * K, resource: BLACK, time: 9 * DAYS, requiredTH: 10, picture: require('../assets/images/Haste_Spell.png')},
  ],
  [BUILDING_TYPES.DARK_SPELLS.SKELETON]: [
    {level: 1, cost: 0, resource: BLACK, time: 0, requiredTH: 1, picture: require('../assets/images/Skeleton_Spell.png')},
    {level: 2, cost: 50 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 10, picture: require('../assets/images/Skeleton_Spell.png')},
    {level: 3, cost: 75 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Skeleton_Spell.png')},
    {level: 4, cost: 100 * K, resource: BLACK, time: 8 * DAYS, requiredTH: 11, picture: require('../assets/images/Skeleton_Spell.png')},
    {level: 5, cost: 125 * K, resource: BLACK, time: 9 * DAYS, requiredTH: 12, picture: require('../assets/images/Skeleton_Spell.png')},
  ],
  //**END DARK_SPELLS**//
  //**SIEGE_MACHINES**//
  [BUILDING_TYPES.SIEGE_MACHINES.WALL_WRECKER]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Wall_Wrecker1.png')},
    {level: 2, cost: 8 * M, resource: ELIXIR, time: 8 * DAYS, requiredTH: 12, picture: require('../assets/images/Wall_Wrecker2.png')},
    {level: 3, cost: 8 * M, resource: ELIXIR, time: 10 * DAYS, requiredTH: 12, picture: require('../assets/images/Wall_Wrecker3.png')},
  ],
  [BUILDING_TYPES.SIEGE_MACHINES.BATTLE_BLIMP]: [
    {level: 1, cost: 0, resource: ELIXIR, time: 0, requiredTH: 1, picture: require('../assets/images/Battle_Blimp1.png')},
    {level: 2, cost: 6 * M, resource: ELIXIR, time: 8 * DAYS, requiredTH: 12, picture: require('../assets/images/Battle_Blimp2.png')},
    {level: 3, cost: 8 * M, resource: ELIXIR, time: 10 * DAYS, requiredTH: 12, picture: require('../assets/images/Battle_Blimp3.png')},
  ],
  //**END SIEGE_MACHINES**//
  //**HEROES**//
  [BUILDING_TYPES.HEROES.KING]: [
    {level: 1, cost: 10 * K, resource: BLACK, time: 0, requiredTH: 7, picture: require('../assets/images/Barbarian_King1.png')},
    {level: 2, cost: 12.5 * K, resource: BLACK, time: 0.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Barbarian_King1.png')},
    {level: 3, cost: 15 * K, resource: BLACK, time: 0.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Barbarian_King1.png')},
    {level: 4, cost: 17.5 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 7, picture: require('../assets/images/Barbarian_King1.png')},
    {level: 5, cost: 20 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 7, picture: require('../assets/images/Barbarian_King1.png')},
    {level: 6, cost: 22.5 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 8, picture: require('../assets/images/Barbarian_King1.png')},
    {level: 7, cost: 25 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 8, picture: require('../assets/images/Barbarian_King1.png')},
    {level: 8, cost: 27.5 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 8, picture: require('../assets/images/Barbarian_King1.png')},
    {level: 9, cost: 30 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 8, picture: require('../assets/images/Barbarian_King1.png')},
    {level: 10, cost: 32.5 * K, resource: BLACK, time: 2 * DAYS, requiredTH: 8, picture: require('../assets/images/Barbarian_King10.png')},
    {level: 11, cost: 35 * K, resource: BLACK, time: 2 * DAYS, requiredTH: 8, picture: require('../assets/images/Barbarian_King10.png')},
    {level: 12, cost: 39 * K, resource: BLACK, time: 2 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King10.png')},
    {level: 13, cost: 43 * K, resource: BLACK, time: 2.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King10.png')},
    {level: 14, cost: 47 * K, resource: BLACK, time: 2.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King10.png')},
    {level: 15, cost: 51 * K, resource: BLACK, time: 2.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King10.png')},
    {level: 16, cost: 55 * K, resource: BLACK, time: 3 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King10.png')},
    {level: 17, cost: 60 * K, resource: BLACK, time: 3 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King10.png')},
    {level: 18, cost: 65 * K, resource: BLACK, time: 3 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King10.png')},
    {level: 19, cost: 70 * K, resource: BLACK, time: 3.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King10.png')},
    {level: 20, cost: 75 * K, resource: BLACK, time: 3.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 21, cost: 80 * K, resource: BLACK, time: 3.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 22, cost: 85 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 23, cost: 90 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 24, cost: 95 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 25, cost: 100 * K, resource: BLACK, time: 4.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 26, cost: 105 * K, resource: BLACK, time: 4.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 27, cost: 110 * K, resource: BLACK, time: 4.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 28, cost: 115 * K, resource: BLACK, time: 5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 29, cost: 120 * K, resource: BLACK, time: 5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 30, cost: 125 * K, resource: BLACK, time: 5 * DAYS, requiredTH: 9, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 31, cost: 129 * K, resource: BLACK, time: 5.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 32, cost: 133 * K, resource: BLACK, time: 5.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 33, cost: 137 * K, resource: BLACK, time: 5.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 34, cost: 141 * K, resource: BLACK, time: 6 * DAYS, requiredTH: 10, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 35, cost: 145 * K, resource: BLACK, time: 6 * DAYS, requiredTH: 10, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 36, cost: 149 * K, resource: BLACK, time: 6 * DAYS, requiredTH: 10, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 37, cost: 153 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 38, cost: 157 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 39, cost: 161 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 40, cost: 165 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 10, picture: require('../assets/images/Barbarian_King20.png')},
    {level: 41, cost: 170 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 42, cost: 173 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 43, cost: 176 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 44, cost: 179 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 45, cost: 182 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 46, cost: 185 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 47, cost: 188 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 48, cost: 191 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 49, cost: 194 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 50, cost: 197 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 51, cost: 200 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 52, cost: 203 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 53, cost: 206 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 54, cost: 209 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 55, cost: 212 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 56, cost: 215 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 57, cost: 218 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 58, cost: 221 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 59, cost: 224 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Barbarian_King41.png')},
    {level: 60, cost: 227 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Barbarian_King41.png')},
  ],
  [BUILDING_TYPES.HEROES.QUEEN]: [
    {level: 1, cost: 40 * K, resource: BLACK, time: 0, requiredTH: 9, picture: require('../assets/images/Archer_Queen1.png')},
    {level: 2, cost: 22.5 * K, resource: BLACK, time: 0.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen1.png')},
    {level: 3, cost: 25 * K, resource: BLACK, time: 0.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen1.png')},
    {level: 4, cost: 27.5 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen1.png')},
    {level: 5, cost: 30 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen1.png')},
    {level: 6, cost: 32.5 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen1.png')},
    {level: 7, cost: 35 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen1.png')},
    {level: 8, cost: 39 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen1.png')},
    {level: 9, cost: 43 * K, resource: BLACK, time: 1 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen1.png')},
    {level: 10, cost: 47 * K, resource: BLACK, time: 2 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen10.png')},
    {level: 11, cost: 51 * K, resource: BLACK, time: 2 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen10.png')},
    {level: 12, cost: 55 * K, resource: BLACK, time: 2 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen10.png')},
    {level: 13, cost: 59 * K, resource: BLACK, time: 2.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen10.png')},
    {level: 14, cost: 63 * K, resource: BLACK, time: 2.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen10.png')},
    {level: 15, cost: 67 * K, resource: BLACK, time: 2.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen10.png')},
    {level: 16, cost: 71 * K, resource: BLACK, time: 3 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen10.png')},
    {level: 17, cost: 75 * K, resource: BLACK, time: 3 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen10.png')},
    {level: 18, cost: 80 * K, resource: BLACK, time: 3 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen10.png')},
    {level: 19, cost: 85 * K, resource: BLACK, time: 3.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen10.png')},
    {level: 20, cost: 90 * K, resource: BLACK, time: 3.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 21, cost: 95 * K, resource: BLACK, time: 3.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 22, cost: 100 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 23, cost: 105 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 24, cost: 110 * K, resource: BLACK, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 25, cost: 115 * K, resource: BLACK, time: 4.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 26, cost: 119 * K, resource: BLACK, time: 4.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 27, cost: 123 * K, resource: BLACK, time: 4.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 28, cost: 127 * K, resource: BLACK, time: 5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 29, cost: 131 * K, resource: BLACK, time: 5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 30, cost: 135 * K, resource: BLACK, time: 5 * DAYS, requiredTH: 9, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 31, cost: 139 * K, resource: BLACK, time: 5.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 32, cost: 143 * K, resource: BLACK, time: 5.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 33, cost: 147 * K, resource: BLACK, time: 5.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 34, cost: 151 * K, resource: BLACK, time: 6 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 35, cost: 155 * K, resource: BLACK, time: 6 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 36, cost: 159 * K, resource: BLACK, time: 6 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 37, cost: 163 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 38, cost: 167 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 39, cost: 171 * K, resource: BLACK, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 40, cost: 175 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 10, picture: require('../assets/images/Archer_Queen20.png')},
    {level: 41, cost: 180 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 42, cost: 182 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 43, cost: 184 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 44, cost: 186 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 45, cost: 188 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 46, cost: 190 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 47, cost: 192 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 48, cost: 194 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 49, cost: 196 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 50, cost: 198 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 51, cost: 200 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 52, cost: 204 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 53, cost: 208 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 54, cost: 212 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 55, cost: 216 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 56, cost: 220 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 57, cost: 224 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 58, cost: 228 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 59, cost: 232 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Archer_Queen41.png')},
    {level: 60, cost: 236 * K, resource: BLACK, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Archer_Queen41.png')},
  ],
  [BUILDING_TYPES.HEROES.GRAND_WARDEN]: [
    {level: 1, cost: 6 * M, resource: ELIXIR, time: 0, requiredTH: 11, picture: require('../assets/images/Grand_Warden1.png')},
    {level: 2, cost: 2.5 * M, resource: ELIXIR, time: 0.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden1.png')},
    {level: 3, cost: 3 * M, resource: ELIXIR, time: 1 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden1.png')},
    {level: 4, cost: 3.5 * M, resource: ELIXIR, time: 1.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden1.png')},
    {level: 5, cost: 4 * M, resource: ELIXIR, time: 2 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden1.png')},
    {level: 6, cost: 4.5 * M, resource: ELIXIR, time: 2.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden1.png')},
    {level: 7, cost: 5 * M, resource: ELIXIR, time: 3 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden1.png')},
    {level: 8, cost: 5.5 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden1.png')},
    {level: 9, cost: 6 * M, resource: ELIXIR, time: 4 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden1.png')},
    {level: 10, cost: 6.5 * M, resource: ELIXIR, time: 4.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 11, cost: 7 * M, resource: ELIXIR, time: 5 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 12, cost: 7.5 * M, resource: ELIXIR, time: 5.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 13, cost: 8 * M, resource: ELIXIR, time: 6 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 14, cost: 8.4 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 15, cost: 8.8 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 16, cost: 9.1 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 17, cost: 9.4 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 18, cost: 9.6 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 19, cost: 9.8 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 20, cost: 10 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 11, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 21, cost: 10 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 22, cost: 10.2 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 23, cost: 10.4 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 24, cost: 10.6 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 25, cost: 10.8 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 26, cost: 11 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 27, cost: 11.2 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 28, cost: 11.4 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 29, cost: 11.6 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Grand_Warden10.png')},
    {level: 30, cost: 11.8 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Grand_Warden10.png')},
  ],
  //**END HEROES**//
  //**BUILDING**//
  [BUILDING_TYPES.BUILDING.GOLD_MINE]: [
    {level: 1, cost: 150, resource: ELIXIR, time: 10, requiredTH: 1, picture: require('../assets/images/Gold_Mine1.png')},
    {level: 2, cost: 300, resource: ELIXIR, time: 60, requiredTH: 1, picture: require('../assets/images/Gold_Mine2.png')},
    {level: 3, cost: 700, resource: ELIXIR, time: 15 * MINUTES, requiredTH: 2, picture: require('../assets/images/Gold_Mine3.png')},
    {level: 4, cost: 1.4 * K, resource: ELIXIR, time: 1 * HOURS, requiredTH: 2, picture: require('../assets/images/Gold_Mine4.png')},
    {level: 5, cost: 3 * K, resource: ELIXIR, time: 1 * HOURS, requiredTH: 3, picture: require('../assets/images/Gold_Mine5.png')},
    {level: 6, cost: 7 * K, resource: ELIXIR, time: 4 * HOURS, requiredTH: 3, picture: require('../assets/images/Gold_Mine6.png')},
    {level: 7, cost: 14 * K, resource: ELIXIR, time: 8 * HOURS, requiredTH: 4, picture: require('../assets/images/Gold_Mine7.png')},
    {level: 8, cost: 28 * K, resource: ELIXIR, time: 16 * HOURS, requiredTH: 4, picture: require('../assets/images/Gold_Mine8.png')},
    {level: 9, cost: 56 * K, resource: ELIXIR, time: 1.5 * DAYS, requiredTH: 5, picture: require('../assets/images/Gold_Mine9.png')},
    {level: 10, cost: 84 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 5, picture: require('../assets/images/Gold_Mine10.png')},
    {level: 11, cost: 168 * K, resource: ELIXIR, time: 2.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Gold_Mine11.png')},
    {level: 12, cost: 336 * K, resource: ELIXIR, time: 3 * DAYS, requiredTH: 8, picture: require('../assets/images/Gold_Mine12.png')},
  ],
  [BUILDING_TYPES.BUILDING.ELIXIR_COLLECTOR]: [
    {level: 1, cost: 150, resource: GOLD, time: 10, requiredTH: 1, picture: require('../assets/images/Elixir_Collector1.png')},
    {level: 2, cost: 300, resource: GOLD, time: 60, requiredTH: 1, picture: require('../assets/images/Elixir_Collector2.png')},
    {level: 3, cost: 700, resource: GOLD, time: 15 * MINUTES, requiredTH: 2, picture: require('../assets/images/Elixir_Collector3.png')},
    {level: 4, cost: 1.4 * K, resource: GOLD, time: 1 * HOURS, requiredTH: 2, picture: require('../assets/images/Elixir_Collector4.png')},
    {level: 5, cost: 3 * K, resource: GOLD, time: 1 * HOURS, requiredTH: 3, picture: require('../assets/images/Elixir_Collector5.png')},
    {level: 6, cost: 7 * K, resource: GOLD, time: 4 * HOURS, requiredTH: 3, picture: require('../assets/images/Elixir_Collector6.png')},
    {level: 7, cost: 14 * K, resource: GOLD, time: 8 * HOURS, requiredTH: 4, picture: require('../assets/images/Elixir_Collector7.png')},
    {level: 8, cost: 28 * K, resource: GOLD, time: 16 * HOURS, requiredTH: 4, picture: require('../assets/images/Elixir_Collector8.png')},
    {level: 9, cost: 56 * K, resource: GOLD, time: 1.5 * DAYS, requiredTH: 5, picture: require('../assets/images/Elixir_Collector9.png')},
    {level: 10, cost: 84 * K, resource: GOLD, time: 2 * DAYS, requiredTH: 5, picture: require('../assets/images/Elixir_Collector10.png')},
    {level: 11, cost: 168 * K, resource: GOLD, time: 2.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Elixir_Collector11.png')},
    {level: 12, cost: 336 * K, resource: GOLD, time: 3 * DAYS, requiredTH: 8, picture: require('../assets/images/Elixir_Collector12.png')},
  ],
  [BUILDING_TYPES.BUILDING.BLACK_DRILL]: [
    {level: 1, cost: 1 * M, resource: ELIXIR, time: 0.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Dark_Elixir_Drill1.png')},
    {level: 2, cost: 1.5 * M, resource: ELIXIR, time: 1.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Dark_Elixir_Drill2.png')},
    {level: 3, cost: 2 * M, resource: ELIXIR, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Dark_Elixir_Drill3.png')},
    {level: 4, cost: 3 * M, resource: ELIXIR, time: 2.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Dark_Elixir_Drill4.png')},
    {level: 5, cost: 4 * M, resource: ELIXIR, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Dark_Elixir_Drill5.png')},
    {level: 6, cost: 5 * M, resource: ELIXIR, time: 5.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Dark_Elixir_Drill6.png')},
  ],
  [BUILDING_TYPES.BUILDING.GOLD_STORAGE]: [
    {level: 1, cost: 300, resource: ELIXIR, time: 10, requiredTH: 1, picture: require('../assets/images/Gold_Storage1.png')},
    {level: 2, cost: 750, resource: ELIXIR, time: 15 * MINUTES, requiredTH: 2, picture: require('../assets/images/Gold_Storage2.png')},
    {level: 3, cost: 1.5 * K, resource: ELIXIR, time: 30 * MINUTES, requiredTH: 2, picture: require('../assets/images/Gold_Storage3.png')},
    {level: 4, cost: 3 * K, resource: ELIXIR, time: 1 * HOURS, requiredTH: 3, picture: require('../assets/images/Gold_Storage4.png')},
    {level: 5, cost: 6 * K, resource: ELIXIR, time: 2 * HOURS, requiredTH: 3, picture: require('../assets/images/Gold_Storage5.png')},
    {level: 6, cost: 12 * K, resource: ELIXIR, time: 3 * HOURS, requiredTH: 3, picture: require('../assets/images/Gold_Storage6.png')},
    {level: 7, cost: 25 * K, resource: ELIXIR, time: 4 * HOURS, requiredTH: 4, picture: require('../assets/images/Gold_Storage7.png')},
    {level: 8, cost: 50 * K, resource: ELIXIR, time: 5 * HOURS, requiredTH: 4, picture: require('../assets/images/Gold_Storage8.png')},
    {level: 9, cost: 100 * K, resource: ELIXIR, time: 8 * HOURS, requiredTH: 5, picture: require('../assets/images/Gold_Storage9.png')},
    {level: 10, cost: 250 * K, resource: ELIXIR, time: 16 * HOURS, requiredTH: 6, picture: require('../assets/images/Gold_Storage10.png')},
    {level: 11, cost: 500 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Gold_Storage11.png')},
    {level: 12, cost: 2.5 * M, resource: ELIXIR, time: 4 * DAYS, requiredTH: 11, picture: require('../assets/images/Gold_Storage12.png')},
    {level: 13, cost: 5 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Gold_Storage13.png')},
  ],
  [BUILDING_TYPES.BUILDING.ELIXIR_STORAGE]: [
    {level: 1, cost: 300, resource: GOLD, time: 10, requiredTH: 1, picture: require('../assets/images/Elixir_Storage1.png')},
    {level: 2, cost: 750, resource: GOLD, time: 15 * MINUTES, requiredTH: 2, picture: require('../assets/images/Elixir_Storage2.png')},
    {level: 3, cost: 1.5 * K, resource: GOLD, time: 30 * MINUTES, requiredTH: 2, picture: require('../assets/images/Elixir_Storage3.png')},
    {level: 4, cost: 3 * K, resource: GOLD, time: 1 * HOURS, requiredTH: 3, picture: require('../assets/images/Elixir_Storage4.png')},
    {level: 5, cost: 6 * K, resource: GOLD, time: 2 * HOURS, requiredTH: 3, picture: require('../assets/images/Elixir_Storage5.png')},
    {level: 6, cost: 12 * K, resource: GOLD, time: 3 * HOURS, requiredTH: 3, picture: require('../assets/images/Elixir_Storage6.png')},
    {level: 7, cost: 25 * K, resource: GOLD, time: 4 * HOURS, requiredTH: 4, picture: require('../assets/images/Elixir_Storage7.png')},
    {level: 8, cost: 50 * K, resource: GOLD, time: 5 * HOURS, requiredTH: 4, picture: require('../assets/images/Elixir_Storage8.png')},
    {level: 9, cost: 100 * K, resource: GOLD, time: 8 * HOURS, requiredTH: 5, picture: require('../assets/images/Elixir_Storage9.png')},
    {level: 10, cost: 250 * K, resource: GOLD, time: 16 * HOURS, requiredTH: 6, picture: require('../assets/images/Elixir_Storage10.png')},
    {level: 11, cost: 500 * K, resource: GOLD, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Elixir_Storage11.png')},
    {level: 12, cost: 2.5 * M, resource: GOLD, time: 4 * DAYS, requiredTH: 11, picture: require('../assets/images/Elixir_Storage12.png')},
    {level: 13, cost: 5 * M, resource: GOLD, time: 7 * DAYS, requiredTH: 12, picture: require('../assets/images/Elixir_Storage13.png')},
  ],
  [BUILDING_TYPES.BUILDING.BLACK_STORAGE]: [
    {level: 1, cost: 600 * K, resource: ELIXIR, time: 0.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Dark_Elixir_Storage1.png')},
    {level: 2, cost: 1.2 * M, resource: ELIXIR, time: 1.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Dark_Elixir_Storage2.png')},
    {level: 3, cost: 1.8 * M, resource: ELIXIR, time: 2 * DAYS, requiredTH: 8, picture: require('../assets/images/Dark_Elixir_Storage3.png')},
    {level: 4, cost: 2.4 * M, resource: ELIXIR, time: 2.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Dark_Elixir_Storage4.png')},
    {level: 5, cost: 3 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Dark_Elixir_Storage5.png')},
    {level: 6, cost: 3.6 * M, resource: ELIXIR, time: 4 * HOURS, requiredTH: 9, picture: require('../assets/images/Dark_Elixir_Storage6.png')},
    {level: 7, cost: 4.2 * M, resource: ELIXIR, time: 7 * HOURS, requiredTH: 12, picture: require('../assets/images/Dark_Elixir_Storage7.png')},
  ],
  [BUILDING_TYPES.BUILDING.CLAN_CASTLE]: [
    {level: 1, cost: 10 * K, resource: GOLD, time: 0, requiredTH: 3, picture: require('../assets/images/Clan_Castle1.png')},
    {level: 2, cost: 100 * M, resource: GOLD, time: 4 * HOURS, requiredTH: 4, picture: require('../assets/images/Clan_Castle2.png')},
    {level: 3, cost: 800 * M, resource: GOLD, time: 12 * HOURS, requiredTH: 6, picture: require('../assets/images/Clan_Castle3.png')},
    {level: 4, cost: 1.8 * M, resource: GOLD, time: 1.5 * HOURS, requiredTH: 8, picture: require('../assets/images/Clan_Castle4.png')},
    {level: 5, cost: 4 * M, resource: GOLD, time: 4 * DAYS, requiredTH: 9, picture: require('../assets/images/Clan_Castle5.png')},
    {level: 6, cost: 7 * M, resource: GOLD, time: 7 * DAYS, requiredTH: 10, picture: require('../assets/images/Clan_Castle6.png')},
    {level: 7, cost: 10 * M, resource: GOLD, time: 10 * DAYS, requiredTH: 11, picture: require('../assets/images/Clan_Castle7.png')},
    {level: 8, cost: 12 * M, resource: GOLD, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Clan_Castle8.png')},
  ],
  [BUILDING_TYPES.BUILDING.ARMY_CAMP]: [
    {level: 1, cost: 250, resource: ELIXIR, time: 5 * MINUTES, requiredTH: 1, picture: require('../assets/images/Army_Camp1.png')},
    {level: 2, cost: 2.5 * K, resource: ELIXIR, time: 1 * HOURS, requiredTH: 2, picture: require('../assets/images/Army_Camp2.png')},
    {level: 3, cost: 10 * K, resource: ELIXIR, time: 2 * HOURS, requiredTH: 3, picture: require('../assets/images/Army_Camp3.png')},
    {level: 4, cost: 100 * K, resource: ELIXIR, time: 5 * HOURS, requiredTH: 4, picture: require('../assets/images/Army_Camp4.png')},
    {level: 5, cost: 250 * K, resource: ELIXIR, time: 16 * HOURS, requiredTH: 5, picture: require('../assets/images/Army_Camp5.png')},
    {level: 6, cost: 750 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 6, picture: require('../assets/images/Army_Camp6.png')},
    {level: 7, cost: 2.25 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Army_Camp7.png')},
    {level: 8, cost: 6.75 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 10, picture: require('../assets/images/Army_Camp8.png')},
    {level: 9, cost: 9 * M, resource: ELIXIR, time: 11 * DAYS + 16 * HOURS, requiredTH: 11, picture: require('../assets/images/Army_Camp9.png')},
    {level: 10, cost: 9 * M, resource: ELIXIR, time: 14 * DAYS, requiredTH: 12, picture: require('../assets/images/Army_Camp10.png')},
  ],
  [BUILDING_TYPES.BUILDING.BARRACK]: [
    {level: 1, cost: 250, resource: ELIXIR, time: 10, requiredTH: 1, picture: require('../assets/images/Barracks1.png')},
    {level: 2, cost: 1 * K, resource: ELIXIR, time: 30 * MINUTES, requiredTH: 1, picture: require('../assets/images/Barracks2.png')},
    {level: 3, cost: 2.5 * K, resource: ELIXIR, time: 1 * HOURS, requiredTH: 1, picture: require('../assets/images/Barracks3.png')},
    {level: 4, cost: 5 * K, resource: ELIXIR, time: 3 * HOURS, requiredTH: 2, picture: require('../assets/images/Barracks4.png')},
    {level: 5, cost: 10 * K, resource: ELIXIR, time: 8 * HOURS, requiredTH: 3, picture: require('../assets/images/Barracks5.png')},
    {level: 6, cost: 80 * K, resource: ELIXIR, time: 12 * HOURS, requiredTH: 4, picture: require('../assets/images/Barracks6.png')},
    {level: 7, cost: 240 * K, resource: ELIXIR, time: 16 * HOURS, requiredTH: 5, picture: require('../assets/images/Barracks7.png')},
    {level: 8, cost: 700 * K, resource: ELIXIR, time: 1.5 * DAYS, requiredTH: 6, picture: require('../assets/images/Barracks8.png')},
    {level: 9, cost: 1.5 * M, resource: ELIXIR, time: 2.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Barracks9.png')},
    {level: 10, cost: 2 * M, resource: ELIXIR, time: 4 * DAYS, requiredTH: 8, picture: require('../assets/images/Barracks10.png')},
    {level: 11, cost: 3 * M, resource: ELIXIR, time: 6 * DAYS, requiredTH: 9, picture: require('../assets/images/Barracks11.png')},
    {level: 12, cost: 4 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 10, picture: require('../assets/images/Barracks12.png')},
    {level: 13, cost: 4 * M, resource: ELIXIR, time: 12 * DAYS, requiredTH: 11, picture: require('../assets/images/Barracks13.png')},
  ],
  [BUILDING_TYPES.BUILDING.DARK_BARRACK]: [
    {level: 1, cost: 750 * K, resource: ELIXIR, time: 2 * DAYS, requiredTH: 7, picture: require('../assets/images/Dark_Barracks1.png')},
    {level: 2, cost: 1.25 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Dark_Barracks2.png')},
    {level: 3, cost: 1.75 * M, resource: ELIXIR, time: 4 * DAYS, requiredTH: 8, picture: require('../assets/images/Dark_Barracks3.png')},
    {level: 4, cost: 2.25 * M, resource: ELIXIR, time: 4.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Dark_Barracks4.png')},
    {level: 5, cost: 2.75 * M, resource: ELIXIR, time: 5.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Dark_Barracks5.png')},
    {level: 6, cost: 3.5 * M, resource: ELIXIR, time: 7 * DAYS, requiredTH: 9, picture: require('../assets/images/Dark_Barracks6.png')},
    {level: 7, cost: 6 * M, resource: ELIXIR, time: 12 * DAYS, requiredTH: 10, picture: require('../assets/images/Dark_Barracks7.png')},
  ],
  [BUILDING_TYPES.BUILDING.LABORATORY]: [
    {level: 1, cost: 25 * K, resource: ELIXIR, time: 30 * MINUTES, requiredTH: 3, picture: require('../assets/images/Laboratory1.png')},
    {level: 2, cost: 50 * K, resource: ELIXIR, time: 3 * HOURS, requiredTH: 4, picture: require('../assets/images/Laboratory2.png')},
    {level: 3, cost: 90 * K, resource: ELIXIR, time: 8 * HOURS, requiredTH: 5, picture: require('../assets/images/Laboratory3.png')},
    {level: 4, cost: 270 * K, resource: ELIXIR, time: 16 * HOURS, requiredTH: 6, picture: require('../assets/images/Laboratory4.png')},
    {level: 5, cost: 500 * K, resource: ELIXIR, time: 1 * DAYS + 8 * HOURS, requiredTH: 7, picture: require('../assets/images/Laboratory5.png')},
    {level: 6, cost: 1 * M, resource: ELIXIR, time: 2 * DAYS + 16 * HOURS, requiredTH: 8, picture: require('../assets/images/Laboratory6.png')},
    {level: 7, cost: 2.5 * M, resource: ELIXIR, time: 3 * DAYS + 8 * HOURS, requiredTH: 9, picture: require('../assets/images/Laboratory7.png')},
    {level: 8, cost: 2.5 * M, resource: ELIXIR, time: 4 * DAYS, requiredTH: 10, picture: require('../assets/images/Laboratory8.png')},
    {level: 9, cost: 2.5 * M, resource: ELIXIR, time: 6 * DAYS, requiredTH: 11, picture: require('../assets/images/Laboratory9.png')},
    {level: 10, cost: 2.5 * M, resource: ELIXIR, time: 8 * DAYS, requiredTH: 12, picture: require('../assets/images/Laboratory10.png')},
  ],
  [BUILDING_TYPES.BUILDING.SPELL_FACTORY]: [
    {level: 1, cost: 200 * K, resource: ELIXIR, time: 12 * HOURS, requiredTH: 5, picture: require('../assets/images/Spell_Factory1.png')},
    {level: 2, cost: 400 * K, resource: ELIXIR, time: 1.5 * DAYS, requiredTH: 6, picture: require('../assets/images/Spell_Factory2.png')},
    {level: 3, cost: 800 * K, resource: ELIXIR, time: 2.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Spell_Factory3.png')},
    {level: 4, cost: 1.6 * M, resource: ELIXIR, time: 3.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Spell_Factory4.png')},
    {level: 5, cost: 3.2 * M, resource: ELIXIR, time: 6 * DAYS, requiredTH: 10, picture: require('../assets/images/Spell_Factory5.png')},
  ],
  [BUILDING_TYPES.BUILDING.DARK_SPELL_FACTORY]: [
    {level: 1, cost: 1.5 * M, resource: ELIXIR, time: 2.5 * DAYS, requiredTH: 8, picture: require('../assets/images/Dark_Spell_Factory1.png')},
    {level: 2, cost: 1.5 * M, resource: ELIXIR, time: 4 * DAYS, requiredTH: 8, picture: require('../assets/images/Dark_Spell_Factory2.png')},
    {level: 3, cost: 3.5 * M, resource: ELIXIR, time: 5.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Dark_Spell_Factory3.png')},
    {level: 4, cost: 4.5 * M, resource: ELIXIR, time: 6.5 * DAYS, requiredTH: 9, picture: require('../assets/images/Dark_Spell_Factory4.png')},
  ],
  [BUILDING_TYPES.BUILDING.WORKSHOP]: [
    {level: 1, cost: 7.5 * M, resource: ELIXIR, time: 6 * DAYS, requiredTH: 12, picture: require('../assets/images/Workshop1.png')},
    {level: 2, cost: 9 * M, resource: ELIXIR, time: 8 * DAYS, requiredTH: 12, picture: require('../assets/images/Workshop2.png')},
  ],
  //**END BUILDING**//
  //**TRAPS**//
  [BUILDING_TYPES.TRAPS.BOMB]: [
    {level: 1, cost: 400, resource: GOLD, time: 0, requiredTH: 3, picture: require('../assets/images/Bomb1.png')},
    {level: 2, cost: 1 * K, resource: GOLD, time: 15 * MINUTES, requiredTH: 3, picture: require('../assets/images/Bomb1.png')},
    {level: 3, cost: 10 * K, resource: GOLD, time: 2 * HOURS, requiredTH: 5, picture: require('../assets/images/Bomb3.png')},
    {level: 4, cost: 100 * K, resource: GOLD, time: 8 * HOURS, requiredTH: 7, picture: require('../assets/images/Bomb3.png')},
    {level: 5, cost: 1 * M, resource: GOLD, time: 1 * DAYS, requiredTH: 8, picture: require('../assets/images/Bomb5.png')},
    {level: 6, cost: 1.5 * M, resource: GOLD, time: 2 * DAYS, requiredTH: 9, picture: require('../assets/images/Bomb5.png')},
    {level: 7, cost: 2 * M, resource: GOLD, time: 3 * DAYS, requiredTH: 10, picture: require('../assets/images/Bomb7.png')},
  ],
  [BUILDING_TYPES.TRAPS.SPRING_TRAP]: [
    {level: 1, cost: 2 * K, resource: GOLD, time: 0, requiredTH: 4, picture: require('../assets/images/Spring_Trap1.png')},
    {level: 2, cost: 500 * K, resource: GOLD, time: 16 * HOURS, requiredTH: 7, picture: require('../assets/images/Spring_Trap1.png')},
    {level: 3, cost: 1 * M, resource: GOLD, time: 1 * DAYS, requiredTH: 8, picture: require('../assets/images/Spring_Trap3.png')},
    {level: 4, cost: 1.5 * M, resource: GOLD, time: 2 * DAYS, requiredTH: 9, picture: require('../assets/images/Spring_Trap3.png')},
    {level: 5, cost: 2 * M, resource: GOLD, time: 3 * DAYS, requiredTH: 10, picture: require('../assets/images/Spring_Trap5.png')},
  ],
  [BUILDING_TYPES.TRAPS.AIR_BOMB]: [
    {level: 1, cost: 4 * K, resource: GOLD, time: 0, requiredTH: 5, picture: require('../assets/images/Air_Bomb1.png')},
    {level: 2, cost: 20 * K, resource: GOLD, time: 4 * HOURS, requiredTH: 5, picture: require('../assets/images/Air_Bomb1.png')},
    {level: 3, cost: 200 * K, resource: GOLD, time: 0.5 * DAYS, requiredTH: 7, picture: require('../assets/images/Air_Bomb3.png')},
    {level: 4, cost: 1.5 * M, resource: GOLD, time: 1 * DAYS, requiredTH: 9, picture: require('../assets/images/Air_Bomb3.png')},
    {level: 5, cost: 2.5 * M, resource: GOLD, time: 2 * DAYS, requiredTH: 11, picture: require('../assets/images/Air_Bomb5.png')},
  ],
  [BUILDING_TYPES.TRAPS.GIANT_BOMB]: [
    {level: 1, cost: 12.5 * K, resource: GOLD, time: 0, requiredTH: 6, picture: require('../assets/images/Giant_Bomb1.png')},
    {level: 2, cost: 75 * K, resource: GOLD, time: 6 * HOURS, requiredTH: 6, picture: require('../assets/images/Giant_Bomb1.png')},
    {level: 3, cost: 750 * K, resource: GOLD, time: 1 * DAYS, requiredTH: 8, picture: require('../assets/images/Giant_Bomb3.png')},
    {level: 4, cost: 2.5 * M, resource: GOLD, time: 3 * DAYS, requiredTH: 10, picture: require('../assets/images/Giant_Bomb3.png')},
    {level: 5, cost: 3.5 * M, resource: GOLD, time: 5 * DAYS, requiredTH: 11, picture: require('../assets/images/Giant_Bomb5.png')},
  ],
  [BUILDING_TYPES.TRAPS.SEEKING_AIR_MINE]: [
    {level: 1, cost: 15 * K, resource: GOLD, time: 0, requiredTH: 7, picture: require('../assets/images/Seeking_Air_Mine1.png')},
    {level: 2, cost: 2 * M, resource: GOLD, time: 1 * DAYS, requiredTH: 9, picture: require('../assets/images/Seeking_Air_Mine1.png')},
    {level: 3, cost: 4 * M, resource: GOLD, time: 3 * DAYS, requiredTH: 10, picture: require('../assets/images/Seeking_Air_Mine3.png')},
  ],
  [BUILDING_TYPES.TRAPS.SKELETON_TRAP]: [
    {level: 1, cost: 6 * K, resource: GOLD, time: 0, requiredTH: 8, picture: require('../assets/images/Skeleton_Trap1.png')},
    {level: 2, cost: 600 * K, resource: GOLD, time: 6 * HOURS, requiredTH: 8, picture: require('../assets/images/Skeleton_Trap1.png')},
    {level: 3, cost: 1.3 * M, resource: GOLD, time: 1 * DAYS, requiredTH: 9, picture: require('../assets/images/Skeleton_Trap3.png')},
    {level: 4, cost: 2 * M, resource: GOLD, time: 2 * DAYS, requiredTH: 10, picture: require('../assets/images/Skeleton_Trap3.png')},
  ],


}
