export default {
  'BUILDER_HUT': 'BUILDER_HUT',
  'TOWN_HALL': 'TOWN_HALL',
  'DEFENSES': {
    'CANON': 'CANON',
    'ARCHER_TOWER': 'ARCHER_TOWER',
    'MORTAR': 'MORTAR',
    'AIR_DEFENSE': 'AIR_DEFENSE',
    'WIZARD_TOWER': 'WIZARD_TOWER',
    'AIR_SWEEPER': 'AIR_SWEEPER',
    'TESLA': 'TESLA',
    'BOMB_TOWER': 'BOMB_TOWER',
    'XBOW': 'XBOW',
    'INFERNO_TOWER': 'INFERNO_TOWER',
    'EAGLE_ARTILLERY': 'EAGLE_ARTILLERY',
    'GIGA_TESLA':'GIGA_TESLA'
  },
  'TROOPS': {
    'BARBARIAN': 'BARBARIAN',
    'ARCHER': 'ARCHER',
    'GIANT': 'GIANT',
    'GOBLIN': 'GOBLIN',
    'WALL_BREAKER': 'WALL_BRECKER',
    'BALLOON': 'BALLOON',
    'WIZARD': 'WIZARD',
    'HEALER': 'HEALER',
    'DRAGON': 'DRAGON',
    'PEKKA': 'PEKKA',
    'BABY_DRAGON': 'BABY_DRAGON',
    'MINER': 'MINER',
    'ELECTRO_DRAGON': 'ELECTRO_DRAGON'
  },
  'DARK_TROOPS': {
    'MINION': 'MINION',
    'HOG_RIDER': 'HOG_RIDER',
    'VALKYRIE': 'VALKYRIE',
    'GOLEM': 'GOLEM',
    'WITCH': 'WITCH',
    'LAVA_HOUND': 'LAVA_HOUND',
    'BOWLER': 'BOWLER',
  },
  'SPELLS': {
    'LIGHTNING': 'LIGHTNING',
    'HEALING': 'HEALING',
    'RAGE': 'RAGE',
    'JUMP': 'JUMP',
    'CLONE': 'CLONE'
  },
  'DARK_SPELLS': {
    'POISON': 'POISON',
    'EARTHQUAKE': 'EARTHQUAKE',
    'HASTE': 'HASTE',
    'SKELETON': 'SKELETON'
  },
  'SIEGE_MACHINES': {
    'WALL_WRECKER': 'WALL_WRECKER',
    'BATTLE_BLIMP': 'BATTLE_BLIMP'
  },
  'HEROES': {
    'KING': 'KING',
    'QUEEN': 'QUEEN',
    'GRAND_WARDEN': 'GRAND_WARDEN',
  },
  'BUILDING': {
    'GOLD_MINE': 'GOLD_MINE',
    'ELIXIR_COLLECTOR': 'ELIXIR_COLLECTOR',
    'BLACK_DRILL': 'BLACK_DRILL',
    'GOLD_STORAGE': 'GOLD_STORAGE',
    'ELIXIR_STORAGE': 'ELIXIR_STORAGE',
    'BLACK_STORAGE': 'BLACK_STORAGE',
    'CLAN_CASTLE': 'CLAN_CASTLE',
    'ARMY_CAMP': 'ARMY_CAMP',
    'BARRACK': 'BARRACK',
    'DARK_BARRACK': 'DARK_BARRACK',
    'LABORATORY': 'LABORATORY',
    'SPELL_FACTORY': 'SPELL_FACTORY',
    'DARK_SPELL_FACTORY': 'DARK_SPELL_FACTORY',
    'WORKSHOP': 'WORKSHOP',
  },
  'TRAPS': {
    'BOMB': 'BOMB',
    'SPRING_TRAP': 'SPRING_TRAP',
    'AIR_BOMB': 'AIR_BOMB',
    'GIANT_BOMB': 'GIANT_BOMB',
    'SEEKING_AIR_MINE': 'SEEKING_AIR_MINE',
    'SKELETON_TRAP': 'SKELETON_TRAP',
  },
  'WALL': 'WALL',





}
